language: objective-c
 
osx_image: xcode7.3
 
before_install:
    - rvm use system
    - sudo gem install cocoapods -v '1.1.1'
 
script:
    xctool -workspace Puzzle.xcworkspace -scheme Puzzle build test -sdk iphonesimulator
