language: objective-c

osx_image: xcode8.2
xcode_project: PersonalStuff.xcodeproj
xcode_scheme: PersonalStuffTests
xcode_sdk: iphonesimulator10.1

before_install:
    - rvm use system
    - sudo gem install cocoapods -v '1.1.1'
    - pod install
    - pod update
 
script:
  - xcodebuild -workspace Puzzle.xcworkspace -scheme PuzzleTests -sdk iphonesimulator build test | xcpretty
